version: '3'
services:
  gitlab-runner:
    image: 'gitlab/gitlab-runner:latest'
    # image: gitlab/ubuntu:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/gitlab-runner
    restart: unless-stopped
